version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./images:/app/images  # Bind mount for images (needed for frontend access)
      - ./backend/data:/app/data  # Bind mount for backend data
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - INDEX_FILE=/app/data/faiss.index
      - PATHS_FILE=/app/data/image_paths.txt
      - IMAGE_DIR=/app/images
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s 